# -*- coding: utf-8 -*-
"""Untitled54.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vgi5hcAYXCJ95DF0Nv3XdMuN9pCgtnWm

### 1. Import Library
Langkah pertama adalah mengimpor semua library yang diperlukan untuk manipulasi data, visualisasi, dan pembangunan model machine learning.
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

"""### 2. Memuat Dataset
Memuat data dari file CSV dan melihat gambaran awal mengenai jumlah data serta distribusi kelas target (Diagnosis).
"""

df = pd.read_csv('diagnosed_cbc_data_v4.csv')
print(f"Jumlah baris dan kolom: {df.shape}")
print(f"Distribusi Kelas Diagnosis:\n{df['Diagnosis'].value_counts()}\n")

"""### 3. Informasi Dataset
Mengecek tipe data setiap kolom dan memastikan struktur dataframe sudah sesuai.
"""

print("\nInfo Dataset:")
df.info()

"""### 4. Pemeriksaan Missing Values
Memastikan tidak ada data yang kosong (null) agar tidak menghambat proses pemodelan.
"""

print("\nJumlah Missing Values per kolom:")
print(df.isnull().sum())

"""### 5. Visualisasi Distribusi Diagnosis
Menampilkan grafik batang untuk melihat seberapa seimbang jumlah sampel pada masing-masing kategori diagnosis.
"""

sns.set_theme(style="whitegrid")
plt.figure(figsize=(10, 6))
sns.countplot(data=df, y='Diagnosis', order=df['Diagnosis'].value_counts().index, palette='viridis')
plt.title('Distribusi Kelas Diagnosis')
plt.xlabel('Jumlah Sampel')
plt.ylabel('Diagnosis')
plt.tight_layout()
plt.show()

"""### 6. Analisis Outlier dengan Boxplot
Visualisasi distribusi fitur numerik untuk mendeteksi adanya pencilan (outlier) sebelum dilakukan standarisasi.
"""

plt.figure(figsize=(14, 8))
sns.boxplot(data=df.drop(columns=['Diagnosis']), palette='Set2')
plt.title('Distribusi Nilai Fitur Numerik (Sebelum Standarisasi)')
plt.xlabel('Fitur')
plt.ylabel('Nilai')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### 7. Pemisahan Fitur dan Target
Memisahkan variabel independen (X) yang berisi hasil tes laboratorium dan variabel dependen (y) yaitu Diagnosis.
"""

X = df.drop(columns=['Diagnosis'])
y = df['Diagnosis']

"""### 8. Encoding Label
Mengubah label kategori diagnosis menjadi bentuk numerik agar dapat diproses oleh algoritma machine learning.
"""

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

"""### 9. Pembagian Data (Train-Test Split)
Membagi dataset menjadi data latih (80%) dan data uji (20%) untuk mengevaluasi performa model nantinya.
"""

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

"""### 10. Standarisasi Fitur
Mengubah skala fitur numerik agar memiliki mean 0 dan standar deviasi 1 menggunakan `StandardScaler`.
"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("Data berhasil di-split dan distandarisasi.\n")

"""### 11. Hyperparameter Tuning: Random Forest
Mencari parameter terbaik untuk model Random Forest menggunakan metode `GridSearchCV`.
"""

rf_model = RandomForestClassifier(random_state=42)
rf_params = {
    'n_estimators': [50, 100, 150],
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 5, 10]
}
print("Tuning Random Forest...")
rf_grid = GridSearchCV(rf_model, rf_params, cv=2, scoring='accuracy', n_jobs=-1)
rf_grid.fit(X_train_scaled, y_train)
best_rf = rf_grid.best_estimator_

"""### 12. Hyperparameter Tuning: SVM
Melakukan tuning parameter untuk model Support Vector Machine (SVM) dengan berbagai kernel dan nilai C.
"""

svm_model = SVC(random_state=42)
svm_params = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly']
}
print("Tuning SVM...")
svm_grid = GridSearchCV(svm_model, svm_params, cv=2, scoring='accuracy', n_jobs=-1)
svm_grid.fit(X_train_scaled, y_train)
best_svm = svm_grid.best_estimator_

"""### 13. Menampilkan Parameter Terbaik
Menampilkan kombinasi parameter optimal yang ditemukan oleh GridSearchCV untuk kedua model.
"""

print(f"\nParameter Terbaik RF  : {rf_grid.best_params_}")
print(f"Parameter Terbaik SVM : {svm_grid.best_params_}\n")

"""### 14. Evaluasi Model
Membuat fungsi untuk menghitung metrik performa (Akurasi, Presisi, Recall, F1-Score) dan membandingkan hasil RF dengan SVM.
"""

def evaluate_model(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='macro', zero_division=0)
    rec = recall_score(y_test, y_pred, average='macro', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='macro', zero_division=0)

    print(f"Hasil Evaluasi: {model_name}")
    print(f"Accuracy  : {acc:.2f}")
    print(f"Precision : {prec:.2f}")
    print(f"Recall    : {rec:.2f}")
    print(f"F1-Score  : {f1:.2f}\n")
    return acc, prec, rec, f1

rf_metrics = evaluate_model(best_rf, X_test_scaled, y_test, "Random Forest (Best Model)")
svm_metrics = evaluate_model(best_svm, X_test_scaled, y_test, "Support Vector Machine (SVM)")

"""### 15. Laporan Klasifikasi Rinci
Menampilkan laporan klasifikasi mendetail per kategori untuk melihat performa model Random Forest secara lebih spesifik.
"""

print("--- Classification Report (Random Forest) ---")
y_pred_rf = best_rf.predict(X_test_scaled)
print(classification_report(y_test, y_pred_rf,
                            target_names=label_encoder.inverse_transform(sorted(list(set(y_encoded)))),
                            labels=sorted(list(set(y_test))),
                            zero_division=0))